
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew bdw-gc
brew bison
brew boost
brew brotli
brew ca-certificates
brew cairo
brew cask
brew cmake
brew coreutils
brew curl
brew dash
brew emacs
brew expat
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew gdbm
brew gettext
brew ghq
brew giflib
brew git
brew glib
brew gmp
brew gnutls
brew go
brew gobject-introspection
brew graphite2
brew guile
brew harfbuzz
brew highlight
brew icu4c@77
brew jansson
brew jpeg
brew jpeg-turbo
brew jq
brew libevent
brew libffi
brew libgit2
brew libidn2
brew libnghttp2
brew libpng
brew libspiro
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew llvm
brew lua
brew lz4
brew lzip
brew lzo
brew m4
brew mackup
brew mas
brew meson
brew mpdecimal
brew nasm
brew ncurses
brew nettle
brew ninja
brew oh-my-posh
brew oniguruma
brew openldap
brew openssl@1.1
brew openssl@3
brew p11-kit
brew pango
brew pcre
brew pcre2
brew peco
brew pixman
brew pkgconf
brew popt
brew python-setuptools
brew python@3.10
brew python@3.11
brew python@3.12
brew python@3.13
brew python@3.9
brew readline
brew rsync
brew rtmpdump
brew rust
brew six
brew sqlite
brew swig
brew texinfo
brew tree
brew tree-sitter
brew unbound
brew util-macros
brew woff2
brew xorgproto
brew xtrans
brew xxhash
brew xz
brew youtube-dl
brew z3
brew zsh
brew zsh-completions
brew zstd

tap homebrew/cask
cask 1password
cask alfred
cask amorphousdiskmark
cask apparency
cask appcleaner
cask betterzip
cask beyond-compare
cask cakebrew
cask candybar
cask carbon-copy-cloner
cask clipy
cask controllermate
cask coteditor
cask coverload
cask deepl
cask dropbox
cask duplicate-file-finder
cask elmedia-player
cask evernote
cask firefox
cask fluid
cask font-m+-nerd-font
cask font-meslo-lg-nerd-font
cask fontforge
cask gimp
cask github
cask google-chrome
cask google-japanese-ime
cask imageoptim
cask iterm2
cask jupyter-notebook-ql
cask karabiner-elements
cask lyrics-master
cask memory-cleaner
cask mi
cask michaelvillar-timer
cask microsoft-auto-update
cask microsoft-office
cask musicbrainz-picard
cask onyx
cask qlcolorcode
cask qlimagesize
cask qlmarkdown
cask qlprettypatch
cask qlstephen
cask qlvideo
cask quicklook-csv
cask quicklook-json
cask quicklookase
cask raycast
cask setapp
cask skitch
cask sourcetree
cask splashtop-streamer
cask suspicious-package
cask timer
cask virtualbox
cask visual-studio-code
cask vivaldi
cask warp
cask webpquicklook

tap homebrew/cask-fonts

tap beeftornado/rmtree

tap jandedobbeleer/oh-my-posh

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask diskwave
